name: mlflow_ci

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  mlflow_ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow==2.19.0 scikit-learn seaborn matplotlib pandas numpy

      - name: Run mlflow project
        # Kita menjalankan MLProject yang ada di dalam folder
        run: mlflow run ./MLProject --env-manager local

      - name: Debug Folder Structure
        # Langkah ini sangat penting untuk melihat di mana folder mlruns berada
        run: ls -R

      - name: Upload MLflow Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ml-model-outputs
          # Menggunakan wildcard (**/) agar folder mlruns pasti ketemu 
          # meskipun lokasinya bergeser di dalam subfolder
          path: "**/mlruns/"
          # Mengatur agar workflow tidak gagal jika folder kosong
          if-no-files-found: warn

      - name: Complete job
        run: echo "Workflow finished successfully"